// Generated by dts-bundle-generator v9.5.1

export type AsyncResult<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
  refresh: () => Promise<void>;
  update: (updater: T | ((prev: T | undefined) => T)) => Promise<void>;
  abort: () => void;
};
export declare function useAsync<T = any, Deps extends any[] = any[]>(
  cb: (signal: AbortSignal, ...deps: Deps) => T | Promise<T>,
  deps?: Deps,
): AsyncResult<T>;

export { useAsync as default };

export {};
